name: Llama38B
cfg_path: Meta-Llama-3-8B/original
truncation_side: right
max_context_len: 256
max_out_len: 256
lora:
  flag: False
  rank: 16
  alpha: 16
  target_modules: [q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj]
  dropout: 0.0
