name: gscept
channels:
  - anaconda
  - conda-forge
  - nvidia
  - nvidia/label/cuda-12.1.0
  - pyg
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - defaults

dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=2.1.0=pyhd8ed1ab_0
  - addict=2.4.0=pyhd8ed1ab_2
  - aom=3.9.1=hac33072_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2024.12.14=hbcca054_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cpython=3.8.20=py38hd8ed1ab_2
  - cuda-cccl=12.1.55=0
  - cuda-command-line-tools=12.1.0=0
  - cuda-compiler=12.1.0=0
  - cuda-cudart=12.1.55=0
  - cuda-cudart-dev=12.1.55=0
  - cuda-cudart-static=12.1.55=0
  - cuda-cuobjdump=12.1.55=0
  - cuda-cupti=12.1.62=0
  - cuda-cupti-static=12.1.62=0
  - cuda-cuxxfilt=12.1.55=0
  - cuda-documentation=12.1.55=0
  - cuda-driver-dev=12.1.55=0
  - cuda-gdb=12.1.55=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-libraries-static=12.1.0=0
  - cuda-nsight=12.1.55=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=12.1.66=0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=12.1.55=0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=12.1.55=0
  - cuda-nvrtc=12.1.55=0
  - cuda-nvrtc-dev=12.1.55=0
  - cuda-nvrtc-static=12.1.55=0
  - cuda-nvtx=12.1.66=0
  - cuda-nvvp=12.1.55=0
  - cuda-opencl=12.1.56=0
  - cuda-opencl-dev=12.1.56=0
  - cuda-profiler-api=12.1.55=0
  - cuda-runtime=12.1.0=0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=12.1.0=0
  - cuda-tools=12.1.0=0
  - cuda-visual-tools=12.1.0=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - dav1d=1.2.1=hd590300_0
  - einops=0.8.0=pyhd8ed1ab_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=3.2.4=1
  - filelock=3.16.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2024.10.0=pyhff2d567_0
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - gds-tools=1.6.0.25=0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py38h6a1700d_1
  - graphite2=1.3.13=h59595ed_1003
  - grpcio=1.62.2=py38h94a1851_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.11.0=py38hbe37b52_0
  - harfbuzz=8.2.1=h3d44ed6_0
  - hdf5=1.12.1=h2b7332f_3
  - hpack=4.0.0=pyh9f0ad1d_0
  - huggingface_hub=0.26.5=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - level-zero=1.20.2=h84d6215_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcublas-static=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcufft-static=11.0.2.4=0
  - libcufile=1.6.0.25=0
  - libcufile-dev=1.6.0.25=0
  - libcufile-static=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcurand-static=10.3.2.56=0
  - libcurl=7.88.1=h251f7ec_2
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusolver-static=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libcusparse-static=12.0.2.55=0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.78.4=hdc74915_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - liblzma=5.6.3=hb9d3cd8_1
  - liblzma-devel=5.6.3=hb9d3cd8_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnpp-static=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.55=0
  - libnvjpeg=12.1.0.39=0
  - libnvjpeg-dev=12.1.0.39=0
  - libnvjpeg-static=12.1.0.39=0
  - libnvvm-samples=12.1.55=0
  - libopenvino=2024.4.0=hac27bb2_0
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_0
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_0
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_0
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_0
  - libopenvino-onnx-frontend=2024.4.0=h56242b0_0
  - libopenvino-paddle-frontend=2024.4.0=h56242b0_0
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_0
  - libopenvino-tensorflow-frontend=2024.4.0=h358ae18_0
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - librsvg=2.56.3=h98fae49_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.2.0=hecacb30_2
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=15.0.7=h0cdce71_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_2
  - networkx=3.1=pyhd8ed1ab_0
  - ninja=1.12.1=h297d8ca_0
  - nsight-compute=2023.1.0.15=0
  - numpy=1.24.4=py38h59b608b_0
  - ocl-icd=2.3.2=hb9d3cd8_2
  - opencl-headers=2024.10.24=h5888daf_0
  - openh264=2.5.0=hf92e6e3_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.4.0=h7b32b05_1
  - packaging=24.2=pyhd8ed1ab_2
  - pango=1.50.14=ha41ecd1_2
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - plyfile=1.1=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - protobuf=4.25.3=py38hb5c7596_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.14=h59595ed_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=he870216_0
  - python_abi=3.8=2_cp38
  - pytorch=2.1.0=py3.8_cuda12.1_cudnn8.9.2_0
  - pytorch-cluster=1.6.3=py38_torch_2.1.0_cu121
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py38_torch_2.1.0_cu121
  - pytorch-sparse=0.6.18=py38_torch_2.1.0_cu121
  - pyyaml=6.0.2=py38h2019614_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - safetensors=0.4.4=py38h4005ec7_0
  - scipy=1.10.1=py38h59b608b_3
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sharedarray=3.2.4=py38haee39ac_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h8bd8927_1
  - sqlite=3.45.3=h5eee18b_0
  - svt-av1=2.3.0=h5888daf_0
  - sympy=1.13.3=pyh2585a3b_104
  - tbb=2021.13.0=hceb3a55_1
  - tensorboard=2.17.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38hcdda232_1
  - tensorboardx=2.6.2.2=pyhd8ed1ab_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - timm=1.0.11=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - torchaudio=2.1.0=py38_cu121
  - torchtriton=2.1.0=py38
  - torchvision=0.15.2=cuda118py38h196c800_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - werkzeug=3.0.6=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.6.3=hbcc6ac9_1
  - xz-gpl-tools=5.6.3=hbcc6ac9_1
  - xz-tools=5.6.3=hb9d3cd8_1
  - yaml=0.2.5=h7f98852_2
  - yapf=0.40.1=pyhd8ed1ab_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py38h62bed22_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - flash-attn==2.7.0.post2
    - huggingface-hub==0.27.1
    - open3d==0.18.0
    - open_clip_torch==2.30.0
    - scipy==1.10.1
    - spconv-cu120==2.3.6
    - torch-geometric==2.6.1
    - -i https://pypi.tuna.tsinghua.edu.cn/simple
