# train
training:
  lr: 3e-5
  epochs: 10

leomix:
  mode: [train]
  dataset: LeoMix
  mix: [gs_scan2cap, gs_scanqa, gs_sqa3d]
  ratio: 1.0
  dataset_wrapper: GSObjPadDatasetWrapper
  dataset_wrapper_args: ${dataset_wrapper_args}
  train_dataloader_args: ${dataloader.train}
  eval_dataloader_args: ${dataloader.eval}

# eval
gs_scan2cap:
  mode: [val, test]
  dataset: GSScan2Cap
  dataset_wrapper: GSObjPadDatasetWrapper
  dataset_wrapper_args: ${dataset_wrapper_args}
  eval_dataloader_args: ${dataloader.eval}
  evaluator: CaptionEvaluator

gs_scanqa:
  mode: [val, test]
  dataset: GSScanQA
  dataset_wrapper: GSObjPadDatasetWrapper
  dataset_wrapper_args: ${dataset_wrapper_args}
  eval_dataloader_args: ${dataloader.eval}
  evaluator: ScanQAEvaluator

gs_sqa3d:
  mode: [val, test]
  dataset: GSSQA3D
  dataset_wrapper: GSObjPadDatasetWrapper
  dataset_wrapper_args: ${dataset_wrapper_args}
  eval_dataloader_args: ${dataloader.eval}
  evaluator: SQA3DEvaluator